"""Shared worlds / fits / truth machinery for the **Causal Inference in
Practice** notebook series (``causal_00`` .. ``causal_10``).

One synthetic brand — *Veranda Home* — walked up the **ladder of evidence**:

    00 the ladder          ->  01 confounding & adjustment
    02 the MMM as a causal model                (estimands, refutation)
    03 structural mediation   04 latent confounders     (structural learning)
    05 measuring one experiment                 (estimator methodology)
    06 calibrating the model  07 many experiments       (evidence composition)
    08 designing the next test                  (economics + identification)
    09 planning the measurement series          (EIG / EVOI / decay)
    10 the closed loop                          (converging on the truth)

The series' epistemic conceit: every notebook is a *possible hidden history*
of the same brand — identical-looking dashboards generated by different causal
worlds (``mmm_framework.synth``), each shipping a **sealed answer key** the
analyst never sees while modelling. Every claim a notebook makes is graded
against that key, and the grading itself is verified: :func:`check_truth`
re-derives each world's per-channel causal contribution from the DGP's own
response constants and asserts it matches the scenario's answer key to float
precision, so if the DGP ever drifts the bake fails loudly instead of silently
mis-grading.

Fit policy (mixed budget): observational MMMs are fast-but-real numpyro NUTS
posteriors (2 chains x 500 draws), fit **once per world** and cached to disk
(``MMMSerializer`` + a cloudpickled panel). The two structural notebooks
(mediation, latent factor) need genuine 4-chain NUTS to mix; they cache their
*derived* tables/arrays so re-bakes are seconds. Delete the cache dir (or set
``MMM_CAUSAL_CACHE``) to force a clean re-fit.

Convention (matches ``lifecycle_common.py``): a plain module imported by the
baked notebooks; bake with ``PYTHONPATH=..`` from ``nbs/`` so both this module
and the installed ``mmm_framework`` resolve. Kernel cwd is ``nbs/causal/``.
"""

from __future__ import annotations

import warnings

warnings.filterwarnings("ignore")

import dataclasses
import hashlib
import json
import os
import tempfile
import time
from pathlib import Path

import cloudpickle
import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Brand + palette
# ---------------------------------------------------------------------------
BRAND = "Veranda Home"
TAGLINE = "a national home & garden retailer"
KPI = "Sales"
SEED = 7

# Channel superset across the series' worlds (4-channel clean-family worlds
# use the first four; the `realistic` world uses all seven).
CHANNELS4 = ["TV", "Search", "Social", "Display"]
CHANNELS7 = ["TV", "Search", "Social", "Display", "Video", "Radio", "Print"]

PALETTE = {
    "TV": "#3b6fb6",
    "Search": "#d98c3f",
    "Social": "#5a9e6f",
    "Display": "#b15a7a",
    "Video": "#6f5aa0",
    "Radio": "#3f8f8f",
    "Print": "#8a6d3b",
    # structural-node colors (mediators / latents)
    "awareness": "#c95d90",
    "consideration": "#7a6fb0",
    "demand": "#708090",
    "economic_health": "#708090",
}

# Editorial ink / accents (consistent with the sibling series).
INK = "#2b2f36"
MUTED = "#9aa7b0"
GOOD = "#4a8d57"
BAD = "#c0504d"
GRID = "#e7ebee"
TRUTH = "#1a1a1a"  # the answer-key color: near-black ticks/lines

# ---------------------------------------------------------------------------
# Cache location (regenerable; delete to force a clean re-fit)
# ---------------------------------------------------------------------------
CACHE = Path(
    os.environ.get("MMM_CAUSAL_CACHE", Path(tempfile.gettempdir()) / "mmm_causal_cache")
)

# Artifacts folder shared by all series (resolved from this file, so it works
# from any kernel cwd): nbs/artifacts/.
ARTIFACTS = Path(__file__).resolve().parents[1] / "artifacts"

# Fast-but-real observational fit budget (numpyro NUTS).
DRAWS, TUNE, CHAINS = 500, 500, 2


def dollars(x: float, unit: str = "") -> str:
    """A readable money string for the dataset's native ($000s) spend units."""
    return f"${x:,.0f}{unit}"


def channel_colors(channels) -> list[str]:
    return [PALETTE.get(c, MUTED) for c in channels]


def style(fig, *, height: int = 440, title: str | None = None, **kwargs):
    """Apply the series' uniform plotly styling to a figure and return it."""
    fig.update_layout(
        height=height,
        margin=dict(l=70, r=30, t=70 if title else 30, b=80),
        font=dict(color=INK),
        title=title,
        plot_bgcolor="white",
        paper_bgcolor="white",
        **kwargs,
    )
    fig.update_xaxes(gridcolor=GRID, zerolinecolor=GRID)
    fig.update_yaxes(gridcolor=GRID, zerolinecolor=GRID)
    return fig


def _quiet_pymc():
    """Silence pymc/arviz advisory chatter before sampling. CRITICAL (not
    ERROR): pymc logs sampler/ESS advisories at ERROR level, and the child
    loggers re-set their own level at import."""
    import logging as _logging

    for _n in (
        "pymc",
        "pymc.sampling",
        "pymc.sampling.mcmc",
        "pymc.stats",
        "pymc.stats.convergence",
        "numpyro",
        "jax",
        "arviz",
        "pytensor",
    ):
        _lg = _logging.getLogger(_n)
        _lg.setLevel(_logging.CRITICAL)
        _lg.propagate = False


def write_artifact(name: str, payload: dict) -> str:
    """Write a JSON answer-sheet artifact the docs pages can quote."""
    ARTIFACTS.mkdir(parents=True, exist_ok=True)
    path = ARTIFACTS / name

    def _safe(o):
        if isinstance(o, dict):
            return {str(k): _safe(v) for k, v in o.items()}
        if isinstance(o, (list, tuple)):
            return [_safe(v) for v in o]
        if isinstance(o, (np.floating, np.integer)):
            return float(o)
        if isinstance(o, np.ndarray):
            return [float(v) for v in o.ravel()]
        return o

    json.dump(_safe(payload), open(path, "w"), indent=2)
    return str(path)


# ---------------------------------------------------------------------------
# Worlds — possible hidden histories of the same brand
# ---------------------------------------------------------------------------
# Factory-default seeds, pinned here so every notebook sees the same histories.
WORLD_SEEDS = {
    "clean": 0,
    "unobserved_confounding": 1,
    "confounding_controlled": 1,  # SAME world as uc + the demand proxy control
    "reverse_causality": 2,
    "realistic": 42,
    "economic_health": 14,
}
FUNNEL_SEED = 21
GEO_SEED = 21


def world(name: str):
    """Build a national scenario with the series' pinned seed (deterministic —
    cheap numpy, rebuilt fresh each call; only *fits* are disk-cached)."""
    from mmm_framework.synth import build

    return build(name, seed=WORLD_SEEDS[name])


def funnel_world(n_weeks: int = 156):
    """The brand-funnel mediation world (TV -> awareness -> consideration ->
    sales, with a latent demand confounder). Not in the SCENARIOS registry —
    its survey blocks can't ride the MFF path."""
    from mmm_framework.synth.dgp import make_brand_funnel

    return make_brand_funnel(seed=FUNNEL_SEED, n_weeks=n_weeks)


def variant(sc, *, keep_controls=None, add_controls=None, roles=None, name=None):
    """A copy of a Scenario with a different *analyst choice* of controls.

    The world (spend, KPI, truth) is untouched — only what the modeler
    conditions on changes. ``roles`` maps control name -> CausalControlRole.
    """
    controls = sc.controls
    if keep_controls is not None:
        controls = controls[list(keep_controls)]
    controls = controls.copy()
    if add_controls:
        for k, v in add_controls.items():
            controls[k] = np.asarray(v, float)
    return dataclasses.replace(
        sc,
        name=name or sc.name,
        controls=controls,
        control_roles=roles if roles is not None else sc.control_roles,
    )


def scenario_for(key: str):
    """The analyst's dataset for each named fit (world x control choice)."""
    from mmm_framework.config import CausalControlRole

    if key in ("uc", "cc", "rc", "clean"):
        return world(
            {
                "uc": "unobserved_confounding",
                "cc": "confounding_controlled",
                "rc": "reverse_causality",
                "clean": "clean",
            }[key]
        )
    if key == "funnel_flat":
        # the brand-funnel world handed to a FLAT MMM (no mediators, surveys
        # ignored) — nb03's "wrong model first" baseline.
        return funnel_world()
    if key == "cc_unmarked":
        # the demand proxy present but left UNMARKED (default precision prior,
        # shrunk toward zero) — the half-closed back-door.
        return variant(
            world("confounding_controlled"), roles={}, name="cc_unmarked"
        )
    if key in ("real_causal", "real_bad"):
        sc = world("realistic")
        roles = {
            "category_demand": CausalControlRole.CONFOUNDER,
            "distribution": CausalControlRole.CONFOUNDER,
        }
        mediator = sc.notes["mediator"]  # brand_awareness
        if key == "real_causal":
            keep = [c for c in sc.controls.columns if c != mediator]
            return variant(sc, keep_controls=keep, roles=roles, name="real_causal")
        # the bad-control trap: the mediator goes in UNMARKED (as a naive
        # modeler would add it) — marking it MEDIATOR is refused at build time.
        return variant(sc, roles=roles, name="real_bad")
    if key in ("econ_naive", "econ_ind", "econ_ind_unmarked"):
        sc = world("economic_health")
        if key == "econ_naive":
            return sc
        from mmm_framework.config import CausalControlRole as _R

        inds = sc.notes["indicators"]  # {name: array}
        roles = {n: _R.CONFOUNDER for n in inds} if key == "econ_ind" else {}
        return variant(sc, add_controls=inds, roles=roles, name=key)
    raise KeyError(f"unknown fit key: {key}")


# ---------------------------------------------------------------------------
# DGP truth helpers — the series' signature machinery
# ---------------------------------------------------------------------------
_TRUTH_WORLDS = {
    "clean", "unobserved_confounding", "confounding_controlled",
    "reverse_causality", "economic_health", "cc_unmarked", "econ_ind",
}


def truth_supported(sc) -> bool:
    """Whether :func:`true_media_term` covers this world's response family."""
    return sc.name.startswith("real") or sc.name in _TRUTH_WORLDS


def true_media_term(sc, channel: str, x) -> np.ndarray:
    """The world's TRUE per-week causal media term for ``channel`` at spend
    path ``x`` (KPI units), reconstructed from the DGP's own response
    constants. Baseline/confounder terms cancel in any spend-perturbation
    difference, so this is exactly what a perfect experiment measures.

    Valid for the additive clean-family worlds (clean / unobserved_confounding
    / confounding_controlled / reverse_causality / economic_health) and the
    ``realistic`` world (whose TV/Video add a mediated awareness path).
    Guarded by :func:`check_truth` — run it in every consuming notebook.
    """
    from mmm_framework.synth import dgp

    if not truth_supported(sc):
        raise ValueError(
            f"true_media_term does not cover world {sc.name!r} "
            "(its DGP has bespoke response constants)"
        )
    x = np.asarray(x, float)
    mx = float(sc.spend[channel].max())
    if sc.name.startswith("real"):
        sat = dgp._logistic_sat(
            dgp._geom_adstock(x / mx, dgp._R_ALPHA[channel]), dgp._R_LAM[channel]
        )
        term = dgp._R_AMP[channel] * sat
        if channel in dgp._R_MEDIATED:  # TV, Video: + b_med * (30 * sat)
            term = term + 4.0 * 30.0 * sat
        return term
    return dgp._AMP[channel] * dgp._logistic_sat(
        dgp._geom_adstock(x / mx, dgp._ALPHA[channel]), dgp._LAM[channel]
    )


def check_truth(sc, rtol: float = 1e-6) -> bool:
    """Self-check: the reconstructed response must reproduce the scenario's own
    sealed answer key (full zero-out lift == true_contribution, per channel).
    If the DGP's constants ever drift, this fails the bake loudly."""
    for c in sc.channels:
        lift = float(true_media_term(sc, c, sc.spend[c].to_numpy(float)).sum())
        truth = float(sc.true_contribution[c])
        if not np.isclose(lift, truth, rtol=rtol):
            raise AssertionError(
                f"truth helper drifted for {sc.name}/{c}: {lift:.3f} != {truth:.3f}"
            )
    return True


def true_readout(sc, channel: str, w0: int, w1: int, *, mult: float = 0.0,
                 se: float | None = None, seed: int = 0) -> dict:
    """What a PERFECT experiment on ``channel`` over weeks ``[w0, w1)`` would
    measure: scale the window's spend by ``mult`` (0 = go dark), difference the
    true response (carryover past the window included), and report the true
    incremental ROAS of the window's spend change. With ``se`` the *observed*
    value adds honest sampling noise — truth + design-implied error, never an
    oracle."""
    x = sc.spend[channel].to_numpy(float)
    x_cf = x.copy()
    x_cf[w0:w1] = x_cf[w0:w1] * mult
    lift = float(
        (true_media_term(sc, channel, x) - true_media_term(sc, channel, x_cf)).sum()
    )
    d_spend = float((x - x_cf).sum())
    roas = lift / d_spend if d_spend else float("nan")
    observed = roas
    if se:
        observed = roas + float(np.random.default_rng(seed).normal(0.0, se))
    return dict(
        channel=channel, w0=w0, w1=w1, mult=mult,
        true_roas=roas, observed=observed, se=se,
        lift=lift, delta_spend=d_spend,
        period=(str(sc.weeks[w0].date()), str(sc.weeks[min(w1, len(sc.weeks)) - 1].date())),
    )


def measurement(sc, channel: str, w0: int, w1: int, *, mult: float = 0.0,
                se: float = 0.12, seed: int = 0, name: str | None = None):
    """A simulated experiment readout as an in-graph ``ExperimentMeasurement``
    (ROAS estimand) plus the readout dict it came from."""
    from mmm_framework.calibration import ExperimentEstimand, ExperimentMeasurement

    r = true_readout(sc, channel, w0, w1, mult=mult, se=se, seed=seed)
    exp = ExperimentMeasurement(
        channel=channel,
        test_period=r["period"],
        value=float(r["observed"]),
        se=float(se),
        estimand=ExperimentEstimand.ROAS,
        distribution="normal",
        name=name or f"{channel}_lift_{r['period'][0]}",
    )
    return exp, r


def true_total_media(sc, spend_df: pd.DataFrame) -> float:
    """The TRUE total media-driven KPI for an arbitrary spend plan (used to
    grade budget allocations against the world, not the model)."""
    return float(
        sum(
            true_media_term(sc, c, spend_df[c].to_numpy(float)).sum()
            for c in sc.channels
        )
    )


# ---------------------------------------------------------------------------
# Observational fits — fit once per (world x control choice), cache, reload
# ---------------------------------------------------------------------------
def _fit_dir(key: str) -> Path:
    return CACHE / f"fit_{key}"


def _model_config(draws: int, tune: int, chains: int):
    from mmm_framework.config import InferenceMethod, ModelConfig

    return ModelConfig(
        inference_method=InferenceMethod.BAYESIAN_NUMPYRO,
        n_draws=draws,
        n_tune=tune,
        n_chains=chains,
        use_parametric_adstock=True,
        optim_seed=0,
    )


def grade(sc, mmm, *, hdi_prob: float = 0.9, seed: int = 0) -> pd.DataFrame:
    """Grade every channel against the sealed answer key, on the model's own
    estimand (counterfactual zero-out contribution) — apples to apples."""
    contrib = mmm.compute_counterfactual_contributions(
        compute_uncertainty=True, hdi_prob=hdi_prob, random_seed=seed
    )
    rows = []
    for c in sc.channels:
        t = float(sc.true_contribution[c])
        e = float(contrib.total_contributions[c])
        lo = float(contrib.contribution_hdi_low[c])
        hi = float(contrib.contribution_hdi_high[c])
        spend = float(sc.spend[c].sum())
        rows.append(
            {
                "channel": c,
                "true": t,
                "est": e,
                "lo": lo,
                "hi": hi,
                "rel_err": (e - t) / abs(t),
                "covered": bool(lo <= t <= hi),
                "true_roas": float(sc.true_roas[c]),
                "est_roas": e / spend,
                "roas_lo": lo / spend,
                "roas_hi": hi / spend,
            }
        )
    return pd.DataFrame(rows).set_index("channel")


def fit_world(key: str, *, draws: int = DRAWS, tune: int = TUNE,
              chains: int = CHAINS, trend: str = "linear",
              verbose: bool = True) -> dict:
    """Fit-or-load the observational MMM for a named (world x controls) fit.

    Returns ``dict(model, sc, panel, grade, diag)``. The fit is a fast-but-real
    numpyro NUTS posterior; the grade table (counterfactual contributions vs
    the sealed key) is computed once at fit time and cached alongside.
    ``trend="none"`` drops the linear trend (cached separately) — used on the
    economic-health world, whose only slow signal IS the latent factor.
    """
    from mmm_framework.serialization import MMMSerializer

    d = _fit_dir(key if trend == "linear" else f"{key}_notrend")
    if (d / "model").exists() and (d / "panel.pkl").exists():
        panel = cloudpickle.load(open(d / "panel.pkl", "rb"))
        model = MMMSerializer.load(str(d / "model"), panel=panel, rebuild_model=True)
        g = pd.read_parquet(d / "grade.parquet")
        diag = json.load(open(d / "diag.json"))
        sc = scenario_for(key)
        if verbose:
            print(f"[{BRAND}] loaded cached fit '{key}' from {d}")
        return dict(model=model, sc=sc, panel=panel, grade=g, diag=diag)

    from mmm_framework.model import BayesianMMM, TrendConfig, TrendType

    sc = scenario_for(key)
    if truth_supported(sc):
        check_truth(sc)
    panel = sc.panel()
    if verbose:
        print(f"[{BRAND}] no cache — fitting '{key}' "
              f"({len(sc.channels)} channels, {len(sc.weeks)} weeks) ...")
    model = BayesianMMM(
        panel,
        _model_config(draws, tune, chains),
        TrendConfig(type=TrendType.LINEAR if trend == "linear" else TrendType.NONE),
    )
    _quiet_pymc()
    t0 = time.perf_counter()
    fit = model.fit(random_seed=SEED, progressbar=False)
    secs = time.perf_counter() - t0
    g = grade(sc, model)
    diag = dict(
        seconds=round(secs, 1),
        rhat_max=float(fit.diagnostics.get("rhat_max", float("nan"))),
        divergences=int(fit.diagnostics.get("divergences", 0) or 0),
        ess_bulk_min=float(fit.diagnostics.get("ess_bulk_min", float("nan"))),
        draws=draws, tune=tune, chains=chains,
    )
    d.mkdir(parents=True, exist_ok=True)
    MMMSerializer.save(model, str(d / "model"), save_trace=True, compress=True)
    cloudpickle.dump(panel, open(d / "panel.pkl", "wb"))
    g.to_parquet(d / "grade.parquet")
    json.dump(diag, open(d / "diag.json", "w"), indent=2)
    if verbose:
        print(f"[{BRAND}] fit '{key}' in {secs:.0f}s "
              f"(rhat_max={diag['rhat_max']:.3f}) — cached to {d}")
    return dict(model=model, sc=sc, panel=panel, grade=g, diag=diag)


def fit_calibrated(key: str, experiments: list, *, draws: int = DRAWS,
                   tune: int = TUNE, chains: int = CHAINS, seed: int | None = None,
                   verbose: bool = True) -> dict:
    """Reload the cached baseline for ``key``, attach in-graph experiment
    likelihoods, and refit (fresh model object each call — fast). Returns
    ``dict(model, sc, grade, diag)``."""
    base = fit_world(key, verbose=False)
    model, sc = base["model"], base["sc"]
    model.add_experiment_calibration(list(experiments))
    _quiet_pymc()
    t0 = time.perf_counter()
    fit = model.fit(draws=draws, tune=tune, chains=chains,
                    random_seed=SEED + 1 if seed is None else seed,
                    progressbar=False)
    secs = time.perf_counter() - t0
    g = grade(sc, model)
    if verbose:
        chs = ", ".join(sorted({e.channel for e in experiments}))
        print(f"[{BRAND}] refit '{key}' with {len(experiments)} experiment(s) "
              f"on [{chs}] in {secs:.0f}s")
    diag = dict(seconds=round(secs, 1),
                rhat_max=float(fit.diagnostics.get("rhat_max", float("nan"))))
    return dict(model=model, sc=sc, grade=g, diag=diag)


# ---------------------------------------------------------------------------
# Structural fit 1 — the brand funnel (StructuralNestedMMM, full NUTS, cached
# derived tables)
# ---------------------------------------------------------------------------
# Mirrors tests/mmm_extensions/test_structural_nested.py::TestBrandFunnelRecovery
# — the pinned spec + fit settings known to recover the funnel.
FUNNEL_FIT = dict(draws=500, tune=1000, chains=4, target_accept=0.95,
                  random_seed=11, nuts_sampler="numpyro")


def _funnel_config():
    from mmm_framework.mmm_extensions import (
        StructuralNestedConfig,
        binary_survey_mediator,
        latent_demand_factor,
        likert_mediator,
    )

    return StructuralNestedConfig(
        mediators=(
            binary_survey_mediator(
                "awareness", ["TV"], persistence="high", affects_outcome=False
            ),
            likert_mediator(
                "consideration",
                ["Display", "Social"],
                parents=["awareness"],
                controls=["Price"],
                latent_factors=["demand"],
                n_categories=5,
            ),
        ),
        latent_factors=(latent_demand_factor("demand"),),
    )


def build_funnel_model(n_weeks: int = 156):
    """The structural model + its world (unfitted) — nb03 uses this to show
    the posited DAG and the prior-predictive machinery."""
    from mmm_framework.mmm_extensions import StructuralNestedMMM

    sc = funnel_world(n_weeks)
    cfg = _funnel_config()
    model = StructuralNestedMMM(
        sc.spend.to_numpy(float),
        sc.y.to_numpy(float),
        sc.channels,
        cfg,
        mediator_data={
            "awareness": sc.notes["awareness_counts"],
            "consideration": sc.notes["consideration_counts"],
        },
        mediator_trials={"awareness": sc.notes["awareness_trials"]},
        X_controls=sc.controls.to_numpy(float),
        control_names=["Price"],
        index=sc.weeks,
    )
    return model, sc


def _band(post, var, q=(0.05, 0.5, 0.95)):
    da = post[var]
    qs = da.quantile(list(q), dim=("chain", "draw")).values
    return {"lo": qs[0], "mid": qs[1], "hi": qs[2], "mean": da.mean(("chain", "draw")).values}


def fit_funnel(verbose: bool = True) -> dict:
    """Fit-or-load the brand-funnel structural model (full NUTS, the expensive
    fit of the series). Caches DERIVED tables/arrays, not the live model:
    mediation / pathway / ROAS DataFrames, latent-state bands vs truth, and
    the named structural-parameter posteriors."""
    d = CACHE / "funnel"
    done = d / "meta.json"
    if done.exists():
        out = dict(
            mediation=pd.read_parquet(d / "mediation.parquet"),
            pathways=pd.read_parquet(d / "pathways.parquet"),
            roas=pd.read_parquet(d / "roas.parquet"),
            params=json.load(open(d / "params.json")),
            meta=json.load(open(done)),
        )
        z = np.load(d / "latents.npz")
        out["latents"] = {k: z[k] for k in z.files}
        out["sc"] = funnel_world()
        if verbose:
            print(f"[{BRAND}] loaded cached funnel fit from {d}")
        return out

    if verbose:
        print(f"[{BRAND}] no cache — fitting the structural funnel model "
              f"(4-chain NUTS, ~20-40 min) ...")
    model, sc = build_funnel_model()
    _quiet_pymc()
    t0 = time.perf_counter()
    res = model.fit(**FUNNEL_FIT)
    secs = time.perf_counter() - t0
    post = res.trace.posterior

    mediation = model.get_mediation_effects()
    pathways = model.get_pathway_effects()
    roas = model.get_channel_roas()

    aw = _band(post, "awareness_probability")
    zc = _band(post, "consideration_latent")
    fd = _band(post, "factor_demand")
    latents = dict(
        p_aw_mean=aw["mean"], p_aw_lo=aw["lo"], p_aw_hi=aw["hi"],
        p_aw_true=np.asarray(sc.notes["p_awareness"], float),
        z_cons_mean=zc["mean"], z_cons_lo=zc["lo"], z_cons_hi=zc["hi"],
        z_cons_true=np.asarray(sc.notes["z_consideration"], float),
        demand_mean=fd["mean"], demand_lo=fd["lo"], demand_hi=fd["hi"],
        demand_true=np.asarray(sc.notes["latent_demand"], float),
    )
    named = [
        "awareness_persistence",
        "beta_TV_to_awareness",
        "lambda_awareness_to_consideration",
        "phi_Price_to_consideration",
        "w_demand_to_consideration",
        "gamma_consideration",
    ]
    params = {
        n: dict(
            mean=float(post[n].mean()),
            lo=float(post[n].quantile(0.05)),
            hi=float(post[n].quantile(0.95)),
        )
        for n in named
        if n in post
    }
    meta = dict(
        seconds=round(secs, 1),
        rhat_max=float(res.diagnostics.get("rhat_max", float("nan"))),
        fit=dict(FUNNEL_FIT),
        n_weeks=len(sc.weeks),
        corr_awareness=float(np.corrcoef(latents["p_aw_mean"], latents["p_aw_true"])[0, 1]),
        corr_consideration=float(np.corrcoef(latents["z_cons_mean"], latents["z_cons_true"])[0, 1]),
        corr_demand=float(abs(np.corrcoef(latents["demand_mean"], latents["demand_true"])[0, 1])),
    )
    d.mkdir(parents=True, exist_ok=True)
    mediation.to_parquet(d / "mediation.parquet")
    pathways.to_parquet(d / "pathways.parquet")
    roas.to_parquet(d / "roas.parquet")
    np.savez_compressed(d / "latents.npz", **latents)
    json.dump(params, open(d / "params.json", "w"), indent=2)
    json.dump(meta, open(done, "w"), indent=2)
    if verbose:
        print(f"[{BRAND}] funnel fit in {secs/60:.0f} min "
              f"(rhat_max={meta['rhat_max']:.3f}) — cached to {d}")
    return dict(mediation=mediation, pathways=pathways, roas=roas,
                params=params, meta=meta, latents=latents, sc=sc)


# ---------------------------------------------------------------------------
# Structural fit 2 — the latent economic-health factor (LatentFactorMMM,
# full NUTS, cached derived tables)
# ---------------------------------------------------------------------------
LATENT_FIT = dict(draws=400, tune=800, chains=4, target_accept=0.9, random_seed=7)


def _garden_path() -> Path:
    return Path(__file__).resolve().parents[2] / "examples" / "garden_models"


def fit_latent(verbose: bool = True) -> dict:
    """Fit-or-load the joint latent-factor MMM on the economic-health world
    (rung C of nb04's adjustment ladder). Caches loadings / ROI / factor-path
    derived tables. NUTS only — MAP is unstable for this ~150-param model."""
    d = CACHE / "latent"
    done = d / "meta.json"
    if done.exists():
        out = dict(
            loadings=pd.read_parquet(d / "loadings.parquet"),
            roi=pd.read_parquet(d / "roi.parquet"),
            grade=pd.read_parquet(d / "grade.parquet"),
            meta=json.load(open(done)),
        )
        z = np.load(d / "factor.npz")
        out["factor"] = {k: z[k] for k in z.files}
        out["sc"] = world("economic_health")
        if verbose:
            print(f"[{BRAND}] loaded cached latent-factor fit from {d}")
        return out

    import sys

    gp = str(_garden_path())
    if gp not in sys.path:
        sys.path.insert(0, gp)
    from latent_factor_mmm import LatentFactorMMM, economic_health_dataset

    from mmm_framework.config import ModelConfig
    from mmm_framework.model import TrendConfig
    from mmm_framework.model.trend_config import TrendType
    from mmm_framework.reporting.helpers import compute_roi_with_uncertainty

    if verbose:
        print(f"[{BRAND}] no cache — fitting the joint latent-factor MMM "
              f"(4-chain NUTS, ~10-30 min) ...")
    dataset, sc = economic_health_dataset(seed=WORLD_SEEDS["economic_health"])
    model = LatentFactorMMM(dataset, ModelConfig(), TrendConfig(type=TrendType.NONE))
    _quiet_pymc()
    t0 = time.perf_counter()
    res = model.fit(**LATENT_FIT)
    secs = time.perf_counter() - t0
    post = res.trace.posterior if hasattr(res, "trace") else model._trace.posterior

    loadings = model.factor_loadings_summary()
    roi = compute_roi_with_uncertainty(model, hdi_prob=0.9)
    g = grade(sc, model)  # same counterfactual estimand as the A/B rung fits
    fb = _band(post, "economic_health")
    factor = dict(
        mean=fb["mean"], lo=fb["lo"], hi=fb["hi"],
        true=np.asarray(sc.notes["latent_econ"], float),
    )
    diags = getattr(res, "diagnostics", {}) or {}
    meta = dict(
        seconds=round(secs, 1),
        rhat_max=float(diags.get("rhat_max") or float("nan")),
        fit=dict(LATENT_FIT),
        corr_factor=float(abs(np.corrcoef(factor["mean"], factor["true"])[0, 1])),
        true_loadings=dict(sc.notes["true_loadings"]),
    )
    d.mkdir(parents=True, exist_ok=True)
    loadings.to_parquet(d / "loadings.parquet")
    roi.to_parquet(d / "roi.parquet")
    g.to_parquet(d / "grade.parquet")
    np.savez_compressed(d / "factor.npz", **factor)
    json.dump(meta, open(done, "w"), indent=2)
    if verbose:
        print(f"[{BRAND}] latent-factor fit in {secs/60:.0f} min "
              f"(factor corr={meta['corr_factor']:.2f}) — cached to {d}")
    return dict(loadings=loadings, roi=roi, grade=g, factor=factor, meta=meta, sc=sc)


# ---------------------------------------------------------------------------
# CSV materializations (planning.design / simulation / optimizer read paths)
# ---------------------------------------------------------------------------
def mff_csv(key: str) -> str:
    """The named fit's dataset as an MFF-long CSV (planning APIs read CSV)."""
    from mmm_framework.synth.mff import scenario_to_mff

    CACHE.mkdir(parents=True, exist_ok=True)
    p = CACHE / f"mff_{key}.csv"
    if not p.exists():
        scenario_to_mff(scenario_for(key)).to_csv(p, index=False)
    return str(p)


# Veranda Home's ten test markets (custom names get seeded baseline offsets,
# budget shares, and per-market effectiveness multipliers in the
# geo_heterogeneous world — regional ROAS genuinely differs).
GEO_DMAS = [
    "Seattle", "Denver", "Boston", "Atlanta", "Chicago",
    "Phoenix", "Portland", "Dallas", "Miami", "Minneapolis",
]


def geo_csv() -> tuple[str, dict]:
    """The brand at 10-market grain (geo_heterogeneous world: per-geo truth in
    the answer key) as an MFF-long CSV. Returns ``(path, truth)``."""
    from mmm_framework.synth import generate_mff

    CACHE.mkdir(parents=True, exist_ok=True)
    p = CACHE / "geo_brand.csv"
    tp = CACHE / "geo_truth.json"
    if p.exists() and tp.exists():
        return str(p), json.load(open(tp))
    df, truth = generate_mff("geo_heterogeneous", seed=GEO_SEED, geographies=GEO_DMAS)
    df.to_csv(p, index=False)
    json.dump(truth, open(tp, "w"), indent=2)
    return str(p), truth


# ---------------------------------------------------------------------------
# Shared chart helpers
# ---------------------------------------------------------------------------
def truth_forest(g: pd.DataFrame, *, roas: bool = False, title: str | None = None,
                 height: int = 420):
    """The series' recurring grade chart: posterior interval dots per channel
    with the sealed truth as near-black ticks. ``g`` is a :func:`grade` table."""
    import plotly.graph_objects as go

    est, lo, hi, tr = ("est_roas", "roas_lo", "roas_hi", "true_roas") if roas else (
        "est", "lo", "hi", "true")
    channels = list(g.index)
    fig = go.Figure()
    for i, c in enumerate(channels):
        fig.add_trace(go.Scatter(
            x=[g.loc[c, lo], g.loc[c, hi]], y=[i, i], mode="lines",
            line=dict(color=PALETTE.get(c, MUTED), width=5), opacity=0.45,
            showlegend=False, hoverinfo="skip"))
        fig.add_trace(go.Scatter(
            x=[g.loc[c, est]], y=[i], mode="markers",
            marker=dict(color=PALETTE.get(c, MUTED), size=12),
            name="estimate (90% HDI)", showlegend=(i == 0),
            hovertemplate=f"{c}: %{{x:.2f}}<extra>estimate</extra>"))
        fig.add_trace(go.Scatter(
            x=[g.loc[c, tr]], y=[i], mode="markers",
            marker=dict(color=TRUTH, symbol="line-ns-open", size=18,
                        line=dict(width=3)),
            name="sealed truth", showlegend=(i == 0),
            hovertemplate=f"{c}: %{{x:.2f}}<extra>truth</extra>"))
    fig.update_yaxes(tickvals=list(range(len(channels))), ticktext=channels,
                     autorange="reversed")
    fig.update_xaxes(title="ROAS (KPI $ per media $)" if roas
                     else "total contribution (KPI units)")
    return style(fig, height=height, title=title)


def dag(nodes: dict, edges: list, *, bad_edges: list = (), title: str | None = None,
        height: int = 380, node_colors: dict | None = None):
    """A small plotly DAG: ``nodes`` maps name -> (x, y); ``edges`` is a list of
    (src, dst); ``bad_edges`` are drawn in the alarm color (open back-doors)."""
    import plotly.graph_objects as go

    node_colors = node_colors or {}
    fig = go.Figure()
    ann = []
    for (a, b) in list(edges) + list(bad_edges):
        x0, y0 = nodes[a]
        x1, y1 = nodes[b]
        color = BAD if (a, b) in set(map(tuple, bad_edges)) else MUTED
        # shorten the arrow so it lands at the node's edge, not its center
        f = 0.18
        ann.append(dict(
            x=x1 - f * (x1 - x0), y=y1 - f * (y1 - y0),
            ax=x0 + f * (x1 - x0), ay=y0 + f * (y1 - y0),
            xref="x", yref="y", axref="x", ayref="y",
            showarrow=True, arrowhead=3, arrowsize=1.4, arrowwidth=2,
            arrowcolor=color))
    for name, (x, y) in nodes.items():
        fig.add_trace(go.Scatter(
            x=[x], y=[y], mode="markers+text", text=[name],
            textposition="bottom center",
            textfont=dict(size=13, color=INK),
            marker=dict(size=34, color=node_colors.get(
                name, PALETTE.get(name, "#dfe6ea")),
                line=dict(color=INK, width=1.5)),
            showlegend=False, hoverinfo="skip"))
    fig.update_layout(annotations=ann)
    fig.update_xaxes(visible=False, range=[-0.15, 1.15])
    fig.update_yaxes(visible=False, range=[-0.25, 1.2])
    return style(fig, height=height, title=title)


def contraction_chart(ledger: pd.DataFrame, *, title: str | None = None,
                      height: int = 440):
    """CI-width per channel as evidence accumulates. ``ledger`` columns:
    ``stage`` (ordered), ``channel``, ``width``."""
    import plotly.graph_objects as go

    fig = go.Figure()
    for c in ledger["channel"].unique():
        sub = ledger[ledger["channel"] == c]
        fig.add_trace(go.Scatter(
            x=sub["stage"], y=sub["width"], mode="lines+markers", name=c,
            line=dict(color=PALETTE.get(c, MUTED), width=2.5),
            marker=dict(size=9)))
    fig.update_yaxes(title="90% interval width", rangemode="tozero")
    fig.update_xaxes(title="evidence folded in")
    return style(fig, height=height, title=title)


__all__ = [
    "BRAND", "TAGLINE", "KPI", "SEED", "CHANNELS4", "CHANNELS7", "PALETTE",
    "INK", "MUTED", "GOOD", "BAD", "GRID", "TRUTH", "CACHE", "ARTIFACTS",
    "DRAWS", "TUNE", "CHAINS", "WORLD_SEEDS", "FUNNEL_SEED", "GEO_SEED", "GEO_DMAS",
    "dollars", "channel_colors", "style", "write_artifact",
    "world", "funnel_world", "variant", "scenario_for",
    "true_media_term", "check_truth", "true_readout", "measurement",
    "true_total_media",
    "grade", "fit_world", "fit_calibrated",
    "FUNNEL_FIT", "build_funnel_model", "fit_funnel",
    "LATENT_FIT", "fit_latent",
    "mff_csv", "geo_csv",
    "truth_forest", "dag", "contraction_chart",
]
