#!/usr/bin/env bash
# MMM Framework — VM provisioning (multiseat Augur appliance).
#
# Downloaded from gs://<release_bucket>/bootstrap/vm_setup.sh and executed by
# the thin Terraform startup script on EVERY boot. Idempotent: package installs
# and one-time steps are guarded by marker files; config files are rewritten
# each boot so Terraform variable changes propagate on the next reboot.
#
# Reads /etc/mmm/deploy.env (written by the startup script from Terraform vars).
# Writes:
#   /etc/mmm/mmm.env                   — API process env (secrets included, 0640 root:mmm)
#   /etc/systemd/system/mmm-api.service
#   /etc/nginx/sites-available/mmm     — frontend + /api reverse proxy (SSE-safe)
#   /usr/local/bin/mmm-update          — release install/rollback tool
set -euo pipefail
exec > >(tee -a /var/log/mmm-setup.log) 2>&1

log() { echo "[vm-setup] $*"; }

# shellcheck disable=SC1091
source /etc/mmm/deploy.env

metadata_token() {
  curl -sf -H "Metadata-Flavor: Google" \
    "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" \
    | python3 -c 'import sys,json;print(json.load(sys.stdin)["access_token"])'
}

secret_fetch() { # secret_fetch <secret-name>
  local token
  token=$(metadata_token)
  curl -sf -H "Authorization: Bearer ${token}" \
    "https://secretmanager.googleapis.com/v1/projects/${GCP_PROJECT}/secrets/$1/versions/latest:access" \
    | python3 -c 'import sys,json,base64;print(base64.b64decode(json.load(sys.stdin)["payload"]["data"]).decode())'
}

# ── 1. Persistent data disk at /data ──────────────────────────────────────────
if ! blkid "${DATA_DISK_DEVICE}" >/dev/null 2>&1; then
  log "formatting data disk ${DATA_DISK_DEVICE}"
  mkfs.ext4 -m 0 -E lazy_itable_init=0,lazy_journal_init=0,discard "${DATA_DISK_DEVICE}"
fi
mkdir -p /data
if ! grep -qs "^${DATA_DISK_DEVICE} /data " /etc/fstab; then
  echo "${DATA_DISK_DEVICE} /data ext4 discard,defaults,nofail 0 2" >>/etc/fstab
fi
mountpoint -q /data || mount /data

# ── 2. Packages (one-time) ────────────────────────────────────────────────────
export DEBIAN_FRONTEND=noninteractive
if [ ! -f /etc/mmm/.packages-installed ]; then
  log "installing system packages"
  apt-get update -q
  # podman + rootless plumbing for the kernel sandbox; nginx for the frontend;
  # build-essential because pytensor compiles C++ at runtime in the API process
  # (host-side model ops) as well as in kernels.
  apt-get install -yq --no-install-recommends \
    podman uidmap slirp4netns passt crun \
    nginx jq curl ca-certificates build-essential
  touch /etc/mmm/.packages-installed
fi

if [ ! -f /etc/mmm/.ops-agent-installed ]; then
  log "installing Google Cloud Ops Agent (logs + metrics)"
  curl -sSo /tmp/add-ops-agent-repo.sh \
    https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh
  bash /tmp/add-ops-agent-repo.sh --also-install \
    && touch /etc/mmm/.ops-agent-installed \
    || log "WARNING: ops agent install failed (non-fatal); logs stay in journald"
fi

if ! command -v uv >/dev/null 2>&1; then
  log "installing uv"
  curl -LsSf https://astral.sh/uv/install.sh \
    | env UV_INSTALL_DIR="/usr/local/bin" INSTALLER_NO_MODIFY_PATH=1 sh
fi

# ── 3. Service user (rootless podman host for the kernel sandbox) ─────────────
if ! id mmm >/dev/null 2>&1; then
  log "creating service user mmm"
  useradd --create-home --shell /bin/bash mmm
fi
# Rootless podman needs subordinate uid/gid ranges…
grep -qs "^mmm:" /etc/subuid || usermod --add-subuids 200000-265535 mmm
grep -qs "^mmm:" /etc/subgid || usermod --add-subgids 200000-265535 mmm
# …and a user runtime dir at boot without a login session (lingering).
loginctl enable-linger mmm
MMM_UID=$(id -u mmm)
systemctl start "user@${MMM_UID}.service" 2>/dev/null || true

mkdir -p /data/workspace /data/state /data/audit
chown -R mmm:mmm /data/workspace /data/state /data/audit
mkdir -p /opt/mmm/releases /opt/mmm/frontends
chown mmm:mmm /opt/mmm/releases

# ── 4. API environment file (secrets fetched fresh each boot) ─────────────────
log "writing /etc/mmm/mmm.env"
AUTH_SECRET=$(secret_fetch "${AUTH_SECRET_NAME}")
BOOTSTRAP_PW=$(secret_fetch "${BOOTSTRAP_PW_SECRET_NAME}")
LLM_KEY=""
if [ -n "${LLM_KEY_SECRET_NAME}" ]; then
  LLM_KEY=$(secret_fetch "${LLM_KEY_SECRET_NAME}")
fi

umask 027
cat >/etc/mmm/mmm.env <<EOF
# Generated by mmm-vm-setup on every boot — do not edit by hand.
# Hosted multiseat posture: fail-closed sandbox + JWT auth (deploy/kernel/README.md).
MMM_AGENT_HOSTED=1
MMM_AGENT_KERNEL=container
MMM_KERNEL_RUNTIME=podman
MMM_KERNEL_TRANSPORT=ipc
MMM_KERNEL_EGRESS=deny
MMM_KERNEL_IMAGE="${KERNEL_IMAGE}"
MMM_KERNEL_MEM="${KERNEL_MEM}"
MMM_KERNEL_CPUS="${KERNEL_CPUS}"
MMM_KERNEL_PIDS="${KERNEL_PIDS}"
MMM_MAX_KERNELS="${MAX_KERNELS}"
MMM_AGENT_WORKSPACE=/data/workspace
MMM_AUDIT_LOG=/data/audit/audit.jsonl
MMM_AUTH_ENABLED=1
MMM_AUTH_PROVIDER=local
MMM_AUTH_SECRET="${AUTH_SECRET}"
MMM_AUTH_BOOTSTRAP_ORG="${BOOTSTRAP_ORG}"
MMM_AUTH_BOOTSTRAP_EMAIL="${BOOTSTRAP_EMAIL}"
MMM_AUTH_BOOTSTRAP_PASSWORD="${BOOTSTRAP_PW}"
MMM_RATELIMIT_ENABLED=1
MMM_RATELIMIT_TRUST_FORWARDED=1
MMM_CORS_ORIGINS="${SITE_ORIGIN}"
MMM_LLM_PROVIDER="${LLM_PROVIDER}"
MMM_LLM_MODEL="${LLM_MODEL}"
MMM_LLM_PROJECT="${GCP_PROJECT}"
MMM_LLM_LOCATION="${LLM_LOCATION}"
MMM_EMBED_PROVIDER="${EMBED_PROVIDER}"
MMM_EMBED_MODEL="${EMBED_MODEL}"
MMM_EMBED_LOCATION="${EMBED_LOCATION}"
GOOGLE_CLOUD_PROJECT="${GCP_PROJECT}"
EOF
if [ -n "${LLM_KEY}" ]; then
  echo "MMM_LLM_API_KEY=\"${LLM_KEY}\"" >>/etc/mmm/mmm.env
fi
if [ -s /etc/mmm/extra.env ]; then
  cat /etc/mmm/extra.env >>/etc/mmm/mmm.env
fi
chown root:mmm /etc/mmm/mmm.env
chmod 0640 /etc/mmm/mmm.env

# ── 5. systemd unit ────────────────────────────────────────────────────────────
# One uvicorn worker by design: the kernel registry and SSE plot/table channels
# live in the API process; scale vertically (machine_type), not with workers.
cat >/etc/systemd/system/mmm-api.service <<EOF
[Unit]
Description=MMM Framework agent API (multiseat Augur)
Wants=network-online.target user@${MMM_UID}.service
After=network-online.target user@${MMM_UID}.service
RequiresMountsFor=/data

[Service]
User=mmm
Group=mmm
EnvironmentFile=/etc/mmm/mmm.env
Environment=HOME=/home/mmm
Environment=XDG_RUNTIME_DIR=/run/user/${MMM_UID}
WorkingDirectory=/data
ExecStart=/opt/mmm/app/.venv/bin/python -m uvicorn mmm_framework.api.main:app --host 127.0.0.1 --port 8000
Restart=always
RestartSec=5
LimitNOFILE=65536
TimeoutStopSec=45
KillMode=mixed
# No NoNewPrivileges / PrivateUsers here: rootless podman requires the setuid
# newuidmap helper to build the kernel sandbox's user namespace.

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable mmm-api

# ── 6. nginx: static frontend + /api reverse proxy (SSE-safe) ─────────────────
cat >/etc/nginx/sites-available/mmm <<'EOF'
# MMM Framework front door.
# - Serves the built React app from /opt/mmm/frontend (SPA fallback).
# - Proxies /api/* to the agent API on :8000, stripping the /api prefix
#   (mirrors frontend/vite.config.ts's dev proxy rewrite).
# - Buffering off so the /chat SSE stream is delivered unbuffered.

# Behind the GCP HTTPS LB the client scheme arrives in X-Forwarded-Proto;
# preserve it, falling back to nginx's own scheme in direct mode.
map $http_x_forwarded_proto $mmm_forwarded_proto {
    default $http_x_forwarded_proto;
    ""      $scheme;
}

server {
    listen 80 default_server;
    server_name _;

    root /opt/mmm/frontend;
    index index.html;

    client_max_body_size 512m;   # CSV/MFF dataset + KB uploads

    gzip on;
    gzip_types application/javascript text/css application/json image/svg+xml;

    location /api/ {
        proxy_pass http://127.0.0.1:8000/;   # trailing slash strips /api
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $mmm_forwarded_proto;
        proxy_set_header Connection "";
        proxy_buffering off;                 # SSE (/chat) must stream
        proxy_cache off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

    location / {
        try_files $uri /index.html;          # SPA routing
    }
}
EOF
rm -f /etc/nginx/sites-enabled/default
ln -sfn /etc/nginx/sites-available/mmm /etc/nginx/sites-enabled/mmm
systemctl enable nginx

# ── 7. mmm-update: release install / upgrade / rollback ───────────────────────
cat >/usr/local/bin/mmm-update <<'EOF'
#!/usr/bin/env bash
# Install a release from the release bucket and (re)start the app.
#   mmm-update            → install whatever releases/CURRENT points at
#   mmm-update <version>  → install/rollback to a specific uploaded version
set -euo pipefail
# shellcheck disable=SC1091
source /etc/mmm/deploy.env
log() { echo "[mmm-update] $*"; }

TOKEN=$(curl -sf -H "Metadata-Flavor: Google" \
  "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" \
  | python3 -c 'import sys,json;print(json.load(sys.stdin)["access_token"])')
gcs() { curl -fsSL -H "Authorization: Bearer ${TOKEN}" "https://storage.googleapis.com/${RELEASE_BUCKET}/$1"; }

VERSION="${1:-}"
if [ -z "${VERSION}" ]; then
  VERSION=$(gcs releases/CURRENT 2>/dev/null || true)
fi
if [ -z "${VERSION}" ]; then
  log "no release uploaded yet — run deploy/gcp/scripts/package_release.sh, then re-run mmm-update"
  exit 0
fi

MMM_UID=$(id -u mmm)
as_mmm() { sudo -H -u mmm env XDG_RUNTIME_DIR="/run/user/${MMM_UID}" "$@"; }

REL="/opt/mmm/releases/${VERSION}"
if [ ! -d "${REL}" ]; then
  log "installing source ${VERSION}"
  mkdir -p "${REL}"
  gcs "releases/${VERSION}/source.tar.gz" | tar -xz -C "${REL}"
  chown -R mmm:mmm "${REL}"
  log "installing python dependencies (uv sync --frozen --no-dev)"
  as_mmm env UV_PYTHON_PREFERENCE=only-managed \
    sh -c "cd '${REL}' && /usr/local/bin/uv python install 3.12 && /usr/local/bin/uv sync --frozen --no-dev"
  # sessions.db is a fixed path inside the package (src/mmm_framework/api/
  # sessions.py) — point it at the persistent disk so auth/org/session state
  # survives releases. SQLite resolves the symlink; WAL sidecars land in
  # /data/state next to the real file.
  ln -sfn /data/state/sessions.db "${REL}/src/mmm_framework/api/sessions.db"
fi

FRONT="/opt/mmm/frontends/${VERSION}"
if [ ! -d "${FRONT}" ]; then
  log "installing frontend ${VERSION}"
  mkdir -p "${FRONT}"
  gcs "releases/${VERSION}/frontend-dist.tar.gz" | tar -xz -C "${FRONT}"
  chmod -R a+rX "${FRONT}"
fi

log "pulling kernel image ${KERNEL_IMAGE}"
printf '%s' "${TOKEN}" \
  | as_mmm podman login --username oauth2accesstoken --password-stdin "${REGISTRY_HOST}"
as_mmm podman pull "${KERNEL_IMAGE}"
log "verifying the kernel image under the real sandbox flags"
as_mmm podman run --rm --read-only --tmpfs /tmp --network none --cap-drop ALL \
  --memory 512m --pids-limit 128 "${KERNEL_IMAGE}" \
  python -c "import mmm_framework, ipykernel; print('kernel sandbox OK')"

log "activating ${VERSION}"
systemctl stop mmm-api 2>/dev/null || true
ln -sfn "${REL}" /opt/mmm/app
ln -sfn "${FRONT}" /opt/mmm/frontend
systemctl start mmm-api
systemctl reload nginx 2>/dev/null || systemctl restart nginx

for _ in $(seq 1 90); do
  if curl -sf http://127.0.0.1:8000/health >/dev/null 2>&1; then
    log "API healthy — release ${VERSION} live"
    exit 0
  fi
  sleep 2
done
log "ERROR: API did not become healthy — inspect: journalctl -u mmm-api -n 200"
exit 1
EOF
chmod 0755 /usr/local/bin/mmm-update

# ── 8. Install the current release (no-op with a friendly message pre-upload) ─
/usr/local/bin/mmm-update || log "WARNING: initial mmm-update failed; fix and re-run 'sudo mmm-update'"

systemctl restart nginx
log "vm setup complete"
