"""
Excel template API routes.

Generate config templates from MFF data and parse completed templates.
"""

import io
import tempfile
from pathlib import Path

import pandas as pd
from fastapi import APIRouter, Depends, File, HTTPException, UploadFile, status
from fastapi.responses import StreamingResponse

from config import Settings, get_settings
from storage import StorageService, get_storage

# Import from mmm_framework
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))

from mmm_framework.excel_config import (
    TemplateGenerator,
    TemplateParser,
    TemplateParseError,
    TemplateValidationError,
)

router = APIRouter(prefix="/templates", tags=["Templates"])


def _read_upload_to_df(content: bytes, filename: str) -> pd.DataFrame:
    """Read uploaded file content into a DataFrame."""
    buffer = io.BytesIO(content)

    if filename.lower().endswith(".csv"):
        return pd.read_csv(buffer)
    elif filename.lower().endswith(".parquet"):
        return pd.read_parquet(buffer)
    elif filename.lower().endswith((".xlsx", ".xls")):
        return pd.read_excel(buffer)
    else:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Unsupported file format: {filename}. Use CSV, Parquet, or Excel.",
        )


@router.post(
    "/generate",
    responses={
        200: {
            "content": {
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": {}
            },
            "description": "Excel configuration template",
        },
        400: {"description": "Invalid file format or MFF structure"},
    },
)
async def generate_template(
    file: UploadFile = File(
        ...,
        description="MFF data file (CSV, Parquet, or Excel) to generate a config template from",
    ),
    settings: Settings = Depends(get_settings),
):
    """
    Generate an Excel configuration template from MFF data.

    Upload your MFF data file and receive a pre-filled Excel template with:
    - **Variables sheet**: All discovered variables with heuristic role classification
    - **Media Settings sheet**: Adstock and saturation defaults for media channels
    - **Model Settings sheet**: Global model configuration with smart defaults
    - **Advanced sheet**: Optional prior overrides for power users

    Edit the template and upload it to `/templates/parse` to create model configs.
    """
    # Read uploaded file
    content = await file.read()
    size_mb = len(content) / (1024 * 1024)

    if size_mb > settings.max_upload_size_mb:
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail=f"File too large. Maximum size is {settings.max_upload_size_mb} MB",
        )

    if not file.filename:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Filename is required",
        )

    try:
        df = _read_upload_to_df(content, file.filename)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Could not read file: {str(e)}",
        )

    # Generate template to a temporary file
    try:
        with tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False) as tmp:
            tmp_path = Path(tmp.name)

        TemplateGenerator.from_mff(df, output_path=tmp_path)

        # Read the generated file and return as streaming response
        with open(tmp_path, "rb") as f:
            xlsx_bytes = f.read()

        # Clean up temp file
        tmp_path.unlink(missing_ok=True)

        return StreamingResponse(
            io.BytesIO(xlsx_bytes),
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={
                "Content-Disposition": "attachment; filename=mmm_config_template.xlsx"
            },
        )

    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Invalid MFF data: {str(e)}",
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Template generation failed: {str(e)}",
        )


@router.post(
    "/parse",
    responses={
        200: {"description": "Parsed configuration objects"},
        400: {"description": "Invalid template structure"},
        422: {"description": "Template validation failed"},
    },
)
async def parse_template(
    file: UploadFile = File(
        ...,
        description="Filled-in Excel configuration template (.xlsx)",
    ),
):
    """
    Parse a completed Excel configuration template.

    Upload a filled-in template (generated by `/templates/generate`) to get
    MFFConfig and ModelConfig objects ready for model fitting.

    Returns JSON with `mff_config`, `model_config`, and `trend_config`.
    """
    if not file.filename or not file.filename.lower().endswith(".xlsx"):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="File must be an Excel file (.xlsx)",
        )

    content = await file.read()

    # Write to temp file for openpyxl
    try:
        with tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False) as tmp:
            tmp.write(content)
            tmp_path = Path(tmp.name)

        mff_config, model_config, trend_config = TemplateParser.parse(tmp_path)

        # Clean up
        tmp_path.unlink(missing_ok=True)

        return {
            "success": True,
            "mff_config": mff_config.model_dump(mode="json"),
            "model_config": model_config.model_dump(mode="json"),
            "trend_config": {
                "type": trend_config.type.value,
                "n_changepoints": trend_config.n_changepoints,
                "changepoint_range": trend_config.changepoint_range,
            },
            "summary": {
                "kpi": mff_config.kpi.name,
                "n_media_channels": len(mff_config.media_channels),
                "media_channels": mff_config.media_names,
                "n_controls": len(mff_config.controls),
                "controls": mff_config.control_names,
                "frequency": mff_config.frequency,
            },
        }

    except TemplateParseError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Template parse error: {str(e)}",
        )
    except TemplateValidationError as e:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Template validation error: {str(e)}",
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Parse failed: {str(e)}",
        )
    finally:
        # Ensure cleanup
        if "tmp_path" in locals():
            tmp_path.unlink(missing_ok=True)
